### ISSUE TITLE
Trying to execute expired trade leads to decoding error

### ISSUE THREAD

**Issue by AndreasEisele** [peshay/btcde#12]
After a call to executeTrade(...) where order had already expired, I get the following output:
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.bitcoin.de
DEBUG:urllib3.connectionpool:https://api.bitcoin.de:443 "POST /v2/trades/F96DZZ?amount=0.02&order_id=F96DZZ&trading_pair=btceur&type=buy HTTP/1.1" 403 None
Traceback (most recent call last):
  File "buy.py", line 50, in <module>
    pprint(btcde.executeTrade(conn, order, "buy", "btceur", amount))
  File "/home/andreas/python/btcde/btcde.py", line 174, in executeTrade
    return APIConnect(conn, 'POST', params, newuri)
  File "/home/andreas/python/btcde/btcde.py", line 121, in APIConnect
    if HandleAPIErrors(r):
  File "/home/andreas/python/btcde/btcde.py", line 61, in HandleAPIErrors
    content = json.load(reader(r.raw))
  File "/usr/lib/python2.7/json/__init__.py", line 287, in load
    return loads(fp.read(),
  File "/usr/lib/python2.7/codecs.py", line 492, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte
```
Don't understand this, it doesn't look helpful.
Vielen Dank & liebe Grüße, Andreas

**Comment by peshay** [comment]
I just tested it with the latest version and received the following error message 
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.bitcoin.de
DEBUG:urllib3.connectionpool:https://api.bitcoin.de:443 "POST /v2/trades/muh?amount=1&order_id=muh&trading_pair=btceur&type=buy HTTP/1.1" 422 None
WARNING:btcde:API Error Code: 26
WARNING:btcde:API Error Message: Invalid order_id
WARNING:btcde:API Error URL: https://api.bitcoin.de/v2/trades/muh?amount=1&order_id=muh&trading_pair=btceur&type=buy
```
Does the issue still persist for you?

**Comment by ghgh2** [comment]
The issue does still persist if you are using an order_id which actually existed, e.g. `AGA7XN`: 

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.bitcoin.de
DEBUG:urllib3.connectionpool:https://api.bitcoin.de:443 "POST /v2/trades/AGA7XN?amount=0&order_id=AGA7XN&trading_pair=btceur&type=buy HTTP/1.1" 403 None
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/btcde.py", line 248, in executeTrade
    return self.APIConnect('POST', p)
  File "/usr/local/lib/python3.6/site-packages/btcde.py", line 167, in APIConnect
    if HandleAPIErrors(r):
  File "/usr/local/lib/python3.6/site-packages/btcde.py", line 97, in HandleAPIErrors
    content = json.load(reader(r.raw))
  File "/usr/local/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.6/codecs.py", line 503, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Comment by pmatos** [comment]
@peshay let me take the opportunity to ask, how to catch that API Error Code 26 you showed in your example?

**Comment by peshay** [comment]
@pmatos I did an `executeTrade` with an order id like `muh` which is not a valid order_id.
If you do the same with an order_id that is valid but doesn't exists, you get the other initially reported error.

**Comment by peshay** [comment]
5e6bd0fae5f334b8bab94e35cb3233aa00755f48
